<a href="https://colab.research.google.com/github/Drakies3172/machine-learning-DIVE-INTO-CODE/blob/main/week2-matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

Let 's call the result matrix is C
so C11 = -1x0 + 2x0 + 3x2 = 6, C12 = -1x2 + 2x2 + 3x9 = 29, C13 = -1x3 + 2x6 + 3x-9 = -20
  C21 = 4x0 + -5x0 + 6x2 = 12, C22 = 4x2 + -5x2 + 6x9=52 , C23 = 4x3 + -5x6 + 6x-9=38
  C31 = 7x0 + 8x0 -9x2= -18, C32 = 7x2 + 8x2 -9x9=-51, C42 =  7x3 + 8x6 -9x-9= -48 



Problem 2

In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(np.matmul(a_ndarray,b_ndarray))
print(np.dot(a_ndarray,b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Problem 3

In [30]:
new_rs = np.array([])
for k in range(len(a_ndarray)):
  for u in range(len(b_ndarray)):
    rs = 0
    for v in range(len(b_ndarray)):
      rs += a_ndarray[k][v] * b_ndarray[v][u]
    new_rs = np.concatenate((new_rs,np.array([rs])))
print(new_rs.reshape(3,3))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


Problem 4

In [39]:
def mamul(a_ndarray,b_ndarray):
  new_rs = np.array([])
  for k in range(len(a_ndarray)):
    for u in range(len(b_ndarray)):
      rs = 0
      for v in range(len(b_ndarray)):
        rs += a_ndarray[k][v] * b_ndarray[v][u]
      new_rs = np.concatenate((new_rs,np.array([rs])))
  try:
    return new_rs.reshape(len(a_ndarray),len(b_ndarray[0]))
  except:
    print("An exception occurred")

Problem 5

In [40]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
mamul(d_ndarray_,e_ndarray)

An exception occurred


Problem 6

In [50]:
b_tranposed = np.transpose(b_ndarray)
result = np.array([])
for i in range(3):
  for k in range(3):
    result = np.concatenate((result,np.array([np.dot(a_ndarray[i],b_tranposed[k])])))
print(result.reshape(3,3))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
